require 'sudoku/member_calculator/base'
require 'sudoku/member_calculator/null_calculator'
require 'sudoku/member_calculator/column'
require 'sudoku/member_calculator/row'
require 'sudoku/member_calculator/box'
